name: CI/CD Pipeline for Next.js

# Trigger on push to main or any pull request to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Use the Node version compatible with your app

    - name: Install dependencies
      run: npm install

    - name: Run tests (optional)
      run: npm test

    - name: Build Next.js app
      run: npm run build

    - name: Deploy to Vercel (optional)
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # You'll need to add this token as a GitHub secret
      run: |
        curl -L https://github.com/vercel/vercel-action/releases/download/v30.0.0/vercel-action.tar.gz | tar xz
        ./vercel-action/deploy.sh
