name: CI/CD for Next.js

on:
  push:
    branches:
      - main # Trigger the action on push to the main branch
  pull_request:
    branches:
      - main # Trigger the action on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # You can change the Node.js version as per your requirement

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Run tests (optional but recommended)
      - name: Run tests
        run: |
          npm run test

      # Build the Next.js app
      - name: Build Next.js app
        run: |
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' # Only deploy on push to the main branch

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Build the Next.js app (again if necessary)
      - name: Build Next.js app
        run: |
          npm run build

      # Deploy to Vercel or other platform (example: Vercel)
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} # Add your Vercel token in GitHub secrets
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} # Add your Vercel project ID in GitHub secrets
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }} # Add your Vercel org ID in GitHub secrets
        run: |
          curl -fsSL https://vercel.com/download -o vercel-cli.deb
          sudo dpkg -i vercel-cli.deb
          vercel --prod --token $VERCEL_TOKEN
