name: React CI/CD Pipeline

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  display:
    runs-on: ubuntu-latest
    env:
      platform: Azure
      region: central
      profile_path: profile/

    steps:
      # Check out the code
      - name: Checkout Code
        run: |
          echo "The platform is ${{ env.platform }}"  # Platform variable correctly accessed
          echo "The region is ${{ env.region }}"      # Region variable correctly accessed
          
      # If you need to add more steps, like installing dependencies or building the project:
      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build
