deploy:
  runs-on: ubuntu-latest
  needs: build
  if: github.ref == 'refs/heads/main'

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Change this to Node.js 20 (or any higher version)

    - name: Install dependencies
      run: |
        npm install

    - name: Build Next.js app
      run: |
        npm run build

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      run: |
        curl -fsSL https://vercel.com/download -o vercel-cli.deb
        sudo dpkg -i vercel-cli.deb
        vercel --prod --token $VERCEL_TOKEN
